### ISSUE TITLE
Feature Proposal: Metric Sink Resource

### ISSUE THREAD

**Issue by hev** [knative/observability#18]
## Problem Summary
Operators lack a simple resource for getting metrics off of the cluster. Additionally, service authors and app developers want to emit metrics in a variety of formats, and consume them from a wide variety of tools and managed services. 

## Evidence

Federation of prometheus across many clusters, and popularity of “serverless” managed services like Datadog, SignalFX, etc. highlight the need for a simple and flexible agent abstraction. 
Insight

Distilling the problem down to a resource that can define (or assume) as set of input and output options allows for enough control for both Operators and Service Developers without much complexity. This is the approach taken by the Telegraf agent. 
Cluster Metric Sink

For operators a key observability need is to monitor the capacity of all clusters. While this can be done using a federated prometheus model an agent based solution can offer the same visibility with less resource (memory) consumption. For this we would propose the following resource definition.

```
apiVersion: pksapi.io/v1beta1
kind: ClusterMetricSink
metadata:
 name: infrastrcture-metrics
spec:
  inputs:
  - type: prometheus
    url: nodeexporter
  outputs:
  - type: datadog
    api-key: secret
```

## Default Inputs & Supported Outputs
It’s likely the cluster sink could assume a set of default inputs (node_exporter, kubestatemetrics, etc.) and only require Operator to specify necessary output details. 

## Metric Sink
Service developers and cluster admins will want to instrument a variety of workloads and may want to send metrics to multiple destinations. 

```
apiVersion: apps.pivotal.io/v1beta1
kind: MetricSink
metadata:
 name: customer-app-metrcs
 namespace: my-workload
spec:
 inputs:
 - type: statsd
   port: 3434
 - type: prometheus
   endpoint: URL
 output:
 - type: datadog
   host: secret
```

## Default Inputs & Supported Outputs
Again the inputs could likely use a common set of defaults for listening for standards such as StatsD but still allow for specification of custom formats and collection endpoints. 

## Security Considerations
This custom resource assumes that operators are ok with metrics being open on the internal network. Operators that do not wish to expose metrics to the network will not be able to utilize these resources.  Additionally the resource will need securely manage secrets in the Kubernetes API. 

## Anti Goal (Storage)
This proposal does not provide a storage solution for metrics, but enables operators to deploy one in their own cluster.
