### ISSUE TITLE
Feature Proposal : Indicator Resource

### ISSUE THREAD

**Issue by hev** [knative/observability#19]
## Problem Summary
Service Authors lack a simple abstraction for defining the Service Level Objectives(SLO) associated with effective operation of their service. This leads to complicated documentation and support playbooks for service authors, even with the ubiquity of tools like Prometheus. 

## Evidence
Evidence of this can be found with most popular monitoring tools. While many package dashboards that offer a good step towards observability very few layer in an approach specific to meeting service level objectives. 

## Insight
A simple markup language could be used to define a custom resource definition that would address this need by pulling together key concept of SLO’s (when it breaks), escalation (how important is it) and documentation/action (how to fix it). This definition could be combined with popular open source controllers for Prometheus and Grafana to vastly simplify the packaging process of this information for Service Authors.

## Indicator Resource
The indicator resource distills these concepts down to a simple YAML file that service authors can include with their service. Here is a sample definition.

```
apiVersion: apps.pivotal.io/v1alpha1
kind: Indicator
metadata:
 name: simple
spec:
 product:
   name: my-component
   version: 1.2.3
 indicators:
 - name: doc_performance_indicator
   promql: avg_over_time(demo_latency{source_id="doc",deployment="$deployment"}[5m])
   documentation: What to do when this triggers
   properties:
     thresholds:
       gte: 80
       level: warning
```

## Prometheus Controller
In order to implement the functionality with Prometheus the scope of this proposal includes the development of a Prometheus controller which would create new Alerting Rules.

## Grafana Controller
In addition to the Prometheus controller for alerting, the indicator protocol can also be used to generate Graphs dashboards which contained charts and documentation. 

## Other Controller (Anti-Goal)
One powerful concept the indicator protocol brings to Kubernetes is the ability to build new controllers and integrations to third party systems (e.g. datadog, stackdriver, etc.). That said, this is outside of the scope of this proposal. 

## Service Author UX
Service authors will need to provide their Service Level Objectives in the example format above when distributed their service.
